### PR TITLE
Cable Lock Mode added

### PR DESCRIPTION
**Pull request by yxkrage**
Added: 
- Sensor for 'Cable Lock Mode'
- Switch for locking and unlocking cable
- Service to set cable lock mode

### CODE REVIEW

**Comment by sockless-coding** [comment]
I looked into the cable lock feature, seems like there are 3 different locks:
image

Also, why the need for the service and sensor? The switch has all that.

**Comment by yxkrage** [comment]
Hmm, interesting. Mine does not look like that. I have these options:
Screenshot 2024-08-21 at 20 15 32

In the response JSON from the charge box api there are three values for the cable lock mode:
`0` = Unlocked
`1` = Locked (Unlock on power loss)
`2` = Locked (Keep locked on power loss)

```json
{
    "serialNumber": 2314768,
    "ocppState": null,
    "connectedToInternet": true,
    "freeCharging": false,
    "ocppConnectionState": null,
    "connector": "NOT_CONNECTED",
    "mode": "ALWAYS_ON",
    "currentLimit": 6,
    "factoryCurrentLimit": 32,
    "switchCurrentLimit": 16,
    "powerMode": "ON",
    "currentChargingCurrent": 0,
    "currentChargingPower": 0,
    "accSessionEnergy": 0,
    "sessionStartTime": null,
    "chargeboxTime": "20:20",
    "accSessionMillis": 0,
    "latestReading": 8533300,
    "chargeStatus": 0,
    "updateStatus": {
        "serialsToUpdate": [],
        "serialsUpdated": [],
        "currentlyUpdating": -1,
        "currentProgress": -1,
        "failedUpdate": "NO_ERROR"
    },
    "currentTemperature": 32,
    "sessionStartValue": -1,
    "nrOfPhases": 1,
    "slaveControlWarning": false,
    "supportConnectionEnabled": false,
    "datetimeConfigured": true,
    "pilotLevel": 6,
    "mainCharger": {
        "reference": null,
        "serialNumber": 2314768,
        "lastContact": 1724264413295,
        "online": false,
        "loadBalanced": false,
        "phase": 0,
        "productId": 132,
        "meterStatus": 0,
        "meterSerial": "303158V",
        "chargeStatus": 0,
        "pilotLevel": 6,
        "accEnergy": 8533300,
        "firmwareVersion": 8,
        "firmwareRevision": 4,
        "wifiCardStatus": 2,
        "connector": "NOT_CONNECTED",
        "accSessionEnergy": 0,
        "sessionStartValue": -1,
        "accSessionMillis": 0,
        "sessionStartTime": null,
        "currentChargingCurrent": 0,
        "currentChargingPower": 0,
        "nrOfPhases": 1,
        "twinSerial": -1,
        "cableLockMode": 0,
        "minCurrentLimit": 6,
        "dipSwitchSettings": 7834,
        "cpuType": 2004993,
        "updateable": false
    },
    "twinCharger": null
}
```

I added a sensor to show which mode the box is currently in:
image

I added the switch to switch between modes `0` and `1`. If you want to set mode `2` you have to use the service... Maybe a second switch can be added for this also...

I hope you find this helpful!

**Comment by sockless-coding** [comment]
I don't have a cable lock on mine (fixed cabled)
So I dug through the code and activated all the hidden features... if all is active, it looks like:
image

I see, since this has 3 states, a SelectEntity would make more sense.

**Comment by yxkrage** [comment]
Ok. That makes sense. I'll see if I can fix a select entity instead of a switch. Can you please provide the JSON output where you have all three cables (as shown in you pic) present?

**Comment by sockless-coding** [comment]
I just showed them using the browser dev tools, it's all controlled by if the device is GLB or TwinMode (`config.twinSerial > 0`)
TwinMode hides the normal switch and shows the Left/Right

**Comment by sockless-coding** [comment]
I've added cable lock support to the new version

**Pull request closed without merging**
